#!/bin/bash

# https://github.com/libgdx/packr

rm -rf jpipeline-macos
rm -rf jpipeline-windows

git clone git@github.com:iamhook/jpipeline.git
cd jpipeline
./gradlew jpipeline-javafx-client:jar
cp jpipeline-javafx-client/build/libs/jpipeline-javafx-client.jar ../jpipeline-javafx-client.jar
cd ../

java -jar packr-all-4.0.0.jar -- params-macos.json

java -jar packr-all-4.0.0.jar -- params-windows.json

rm -rf jpipeline
rm jpipeline-javafx-client.jar

