#!/bin/bash
rm -rf jpipeline-macos
rm -rf jpipeline-windows

git clone git@github.com:iamhook/jpipeline.git
cd jpipeline
./gradlew jpipeline-javafx-client:jar
cp jpipeline-javafx-client/build/libs/jpipeline-javafx-client.jar ../jpipeline-javafx-client.jar
cd ../

rm -rf jpipeline

java -jar packr-all-4.0.0.jar \
     --platform mac \
     --jdk OpenJDK11U-jre_x64_mac_hotspot_11.0.11_9.tar.gz \
     --useZgcIfSupportedOs \
     --output jpipeline-macos \
     -- params.json

java -jar packr-all-4.0.0.jar \
     --platform windows64 \
     --jdk OpenJDK11U-jre_x64_windows_hotspot_11.0.11_9.zip \
     --useZgcIfSupportedOs \
     --output jpipeline-windows \
     -- params.json
